### ISSUE TITLE
Unable to save files using the .x3g plugin

### ISSUE THREAD

**Issue by LukeBonathan** [Ghostkeeper/X3GWriter#15]
I've been trying to find out how to save files from Cura using the x3g plugin.

I have the latest cura build and installed the plugin through the package centre.

When I try to save the files save but the output file contains no data.

Files are located here:

‎⁨HD⁩ ▸ ⁨Users⁩ ▸ ⁨luke⁩ ▸ ⁨Library⁩ ▸ ⁨Application Support⁩ ▸ ⁨cura⁩ ▸ ⁨3.4⁩ ▸ ⁨plugins⁩ ▸ ⁨X3GWriter⁩

here is the log

[cura.log](https://github.com/Ghostkeeper/X3GWriter/files/2430377/cura.log)

Any help would be appreciated

**Comment by castaway** [comment]
I just had the a similar issue .. in the cura.log I get an error "Permission denied", and it turned out that the "gpx" executable wasnt set to executable at all.. (that is under linux, it had no "x" permission.. chmod +x gpx" fixed it for me..

Hmm, yours is macos, and I'm not sure if its the same issue, you could try running it by hand? Yours says:

2018-09-29 08:21:01,626 - DEBUG - [Thread-3] X3GWriter.X3GWriter.gpx_command [112]: GPX command: /Users/luke/Library/Application Support/cura/3.4/plugins/X3GWriter/gpx_macos -c /var/folders/nj/gff0hl517037sgn8wll55phr0000gn/T/tmp1cobc7hh /var/folders/nj/gff0hl517037sgn8wll55phr0000gn/T/tmpr55s7g0u /var/folders/nj/gff0hl517037sgn8wll55phr0000gn/T/tmpnj9raf1_
2018-09-29 08:21:01,670 - DEBUG - [Thread-3] X3GWriter.X3GWriter.write [46]: (None, None)

**Comment by LukeBonathan** [comment]
Initially my writer wasn't executable and after resetting a bunch of os permissions on onyx I managed to run the command as you say. Now it generates a file and saves it but there is nothing in the actual file...

Luke

**Comment by Ghostkeeper** [comment]
In the latest version (1.1.3) I've added execution permissions to the executable files programmatically: https://github.com/Ghostkeeper/X3GWriter/commit/55279360d351bd4006ce5f3b3a1dbd020f8112bb

The reason was that it seems that MacOS didn't maintain the executable permissions from the zip file that contains the plug-in while downloading it from the Toolbox. Previously this plug-in was never tested on MacOS. This is the first time I'm hearing that the issue also existed on Linux though.

Can you update X3GWriter through the toolbox in Cura 3.5 and try again?

> Now it generates a file and saves it but there is nothing in the actual file...

This is an indication that the GPX executable didn't run or didn't work. I'd love to see a Cura log for that!

**Comment by TheFirstAxel** [comment]
This is what mine would do when I was getting the "nonetype attribute write" or whatever error. It would create an empty X3G file. I wonder if it is that problem after fixing the permissions

**Comment by elljayd2** [comment]
New user here. I'm also having problems saving .x3g files .. files contain no (zero bytes) content. Win10, Cura 3.5.1 .. X3GWriter 1.1.3 installed via toolbox. Any advice would be appreciated.

Thanks,
Larry

**Comment by Ghostkeeper** [comment]
Hey Larry, could you post the log file of what happens when you try?

**Comment by elljayd2** [comment]
Sure .. here you go .. thanks for having a look. The .log file content is a bit cryptic to me, but hopefully it's helpful. (I'm hoping I got the 'add file' right).

Thanks,
Larry

[cura.log](https://github.com/Ghostkeeper/X3GWriter/files/2566287/cura.log)

**Comment by Ghostkeeper** [comment]
This is the part of the log that is relevant to this plug-in (thanks for already sanitising your personal information):

    2018-11-09 06:51:36,932 - DEBUG - [Thread-6] X3GWriter.X3GWriter.gpx_executable [109]: GPX executable: C:\Users\User\AppData\Roaming\cura\3.5\plugins\X3GWriter\X3GWriter\gpx.exe
    2018-11-09 06:51:36,933 - DEBUG - [Thread-6] X3GWriter.X3GWriter.gpx_command [130]: GPX command: C:\Users\User\AppData\Roaming\cura\3.5\plugins\X3GWriter\X3GWriter\gpx.exe -c C:\Users\User\AppData\Local\Temp\tmpgx46a7hl C:\Users\User\AppData\Local\Temp\tmp6anezye0 C:\Users\User\AppData\Local\Temp\tmpzdnbyz2d
    2018-11-09 06:51:37,142 - DEBUG - [Thread-6] X3GWriter.X3GWriter.write [62]: (None, None)

It's strange to me that it says `(None, None)` at the end there. Thanks to your log I fixed that with release 1.1.4. It probably won't solve your problem but I hope it'll make it easier to debug it.

**Comment by elljayd2** [comment]
Well, I tried to load 1.1.4, but I think I'm maybe heading even further in the wrong direction now. I couldn't locate it in the Toolbox (i.e. Marketplace in Cura 3.6.0), couldn't drag/drop the plugin onto the Cura workspace (Cura says it can't open the file) .. so I tried getting it going via the Source code route. I think I've extracted it to the correct location, but trying to now see if it's installed via Marketplace installed plugins reliably crashes Cura every time I try it. So, still spinning my wheels here.

I did think I was onto something the other evening when my firewall was blocking .gpx (for another slicer I use - Simplify3D), so I enabled that .. but had the same results.

Think I'm gonna just punt on Cura and stick with Simplify3D for the time being .. haven't had any problems there generating the .x3g files. (Or maybe I'll try to give this a go on my OS X machines if I get some time .. will see what happens there).

Thanks,
Larry

**Comment by Ghostkeeper** [comment]
Yeah, sorry. The Marketplace of Cura hasn't been friendly to me. I was the first user to upload something to the Contributor portal - by way of alpha test - and it turns out that they manually renamed my plug-in from `X3GWriter` to `x3gwriter` which causes Cura to brick when upgrading from the CamelCase version 1.1.3 to the lowercase version 1.1.4. I quickly took my plug-in offline for this reason, lest more people brick their computers once 3.6 goes live in half an hour.

The only way out is to remove the configuration folders of Cura (at `C:\Users\<you>\AppData\Roaming\cura`) which resets Cura to factory defaults completely. Otherwise it just won't start.

If it's any consolidation, the 1.1.4 version wouldn't have solved your issue; it would only make it easier to debug for me what's going on by your logs...

**Comment by Ghostkeeper** [comment]
This should be fixed in the latest release (1.1.7+). Please update and try again. There was an additional problem in the Marketplace that file permissions were not preserved when packaging the plug-in on their server.

**Comment by elljayd2** [comment]
Hi - short story for me is that (with Win10) I'm still seeing 0 byte .x3g files with 1.1.7 .. doesn't appear to be any change.

Larry

**Comment by dos145** [comment]
Hi everyone !

The 0kb problem appears for me on the Cura 4.7.0 with X3GWriter 1.1.11
I solve it by starting Cura as admin ...

Thanks a lot to Ghostkeeper to let us use our old Replicator despite of the end of support of makerbot !

**Comment by kleinwareio** [comment]
Also happening with me. Win 10, Cura 4.8.0, X3GWriter 1.1.11. Running as admin as dos145 suggested also appears to avoid the issue for me.
