### ISSUE TITLE
Folder to put my gpx.ini

### ISSUE THREAD

**Issue by FHEMUser** [Ghostkeeper/X3GWriter#31]
Hello.
I am using gpx win32-1.3 on command line long time before.
Now i want to use X3GWriter with Cura 3.6
I want to use my ini file that i am using before.

To what folder i must copy my ini file so gpx will use it ?
Must i use a specific filename or must i edit anything in the py file to told gpx use my ini ?

**Comment by Ghostkeeper** [comment]
This plug-in writes its own INI file and instructs GPX to use that one instead. That way, it will use the information in Cura, since Cura has settings for practically everything inside that INI.

The code that writes this INI file is located here:

https://github.com/Ghostkeeper/X3GWriter/blob/b55d893ca59b1b50becd372adb9a171ec9e5cf77/X3GWriter.py#L173-L236

It's not possible to configure X3GWriter to use a custom INI file rather than Cura's settings. So normally you'd edit Cura's settings instead of providing an INI file.

If you're up for modding the plug-in, then you should replace `temp_cfg_name` with the name of your INI file in this line:

https://github.com/Ghostkeeper/X3GWriter/blob/b55d893ca59b1b50becd372adb9a171ec9e5cf77/X3GWriter.py#L57
