### ISSUE TITLE
Couldn't save file: "charmap" codec can't encode character '\u200b' 

### ISSUE THREAD

**Issue by iBNB-Loussa** [Ghostkeeper/X3GWriter#42]
Dear Ghostkeeper,

first off, great thanks for the X3GWriter plugin. I was trying to save a file under Cura 4.8.0 for the QidiTech printer using your plugin but unfortunately, I couldn't do so due to an issue with ASCII characters somewhere. 

Please find attached a screenshot for cura`s interface with the error message and the printer parameters. 

Is there any cure for that problem ? 

Thanks

![issue](https://user-images.githubusercontent.com/78174476/106191682-31d65800-6179-11eb-9026-740c42c963d6.JPG)

!

**Comment by Ghostkeeper** [comment]
Hi!

Unicode character 200B is a [zero-width space](http://www.unicode-symbol.com/u/200B.html). It's essentially point at which words are allowed to wrap, but it's completely invisible (as opposed to a normal space). That's why the start g-code looks normal. But I bet that there's a zero-width space in there somewhere. Perhaps if you copied that start g-code from some website the zero-width space came along.

As a workaround, I suggest that you go through the start and end g-code with the arrow keys and see if there's any point at which the cursor doesn't advance when you press the right arrow key. That's where the zero-width space will be. Alternatively, you could manually type the whole start and end g-code in rather than copy-pasting it.

As a fix, I think this plug-in should filter out any characters that it can't send to the GPX converter application.

**Comment by Ghostkeeper** [comment]
This is fixed by https://github.com/Ghostkeeper/X3GWriter/commit/15d629706af1232e58a46b8f18dacca9d2941980. Thanks for the report!
